// UI (trybuild) test: `#[upgradeable]` works without a user `#[contractimpl]` block.
//
// Purpose:
// - Ensures the macro-generated `impl utils::upgradeable::Upgradeable for Contract` is enough to
//   provide the upgrade/migrate entrypoints.
// - Covers the common pattern where the contract does not define any custom entrypoints.

use soroban_sdk::{contract, Address, Bytes, BytesN, Env};

#[contract]
#[common_macros::ownable]
#[common_macros::upgradeable(no_migration)]
pub struct MyContract;

#[allow(dead_code)]
fn typecheck(env: &Env, owner: &Address) {
    // Ownable initializer helper exists (not necessarily an entrypoint).
    MyContract::init_owner(env, owner);

    // Upgradeable entrypoints exist (generated by the macro).
    let hash = BytesN::<32>::from_array(env, &[0u8; 32]);
    let migration_data = Bytes::new(env);
    MyContract::upgrade(env, &hash);
    MyContract::migrate(env, &migration_data);
}

fn main() {}
