// Runtime tests: OAppCore behavior generated by `#[oapp]`.

use super::{TestOApp, TestOAppClient};
use oapp::oapp_core::{OAppCoreStorage, PeerSet};
use soroban_sdk::{
    contract, contractimpl,
    testutils::{Address as _, MockAuth, MockAuthInvoke},
    xdr::{ScErrorCode, ScErrorType},
    Address, BytesN, Env, Error, IntoVal,
};
use utils::testing_utils::assert_contains_event;

/// Minimal endpoint stub used to verify `OAppCore::set_delegate` forwards calls.
#[contract]
pub struct MockEndpoint;

#[contractimpl]
impl MockEndpoint {
    pub fn set_delegate(env: Env, oapp: Address, new_delegate: Option<Address>) {
        if let Some(d) = new_delegate {
            env.storage().instance().set(&oapp, &d);
        } else {
            env.storage().instance().remove(&oapp);
        }
    }

    pub fn delegate(env: Env, oapp: Address) -> Option<Address> {
        env.storage().instance().get(&oapp)
    }
}

#[test]
fn oapp_version_default() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    // Default `OAppCore::oapp_version` should be callable without initialization.
    assert_eq!(client.oapp_version(), (1u64, 1u64));
}

#[test]
fn endpoint_roundtrip() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    // Before init, `endpoint()` unwraps storage and should fail.
    assert!(client.try_endpoint().is_err());

    let owner = Address::generate(&env);
    let endpoint = Address::generate(&env);
    client.init(&owner, &endpoint);

    assert_eq!(client.endpoint(), endpoint);
}

#[test]
fn set_peer_requires_auth_and_updates_storage() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let owner = Address::generate(&env);
    let endpoint = Address::generate(&env);
    client.init(&owner, &endpoint);

    let eid: u32 = 101;
    let peer = Some(BytesN::<32>::from_array(&env, &[7u8; 32]));

    // Peer is None when unset.
    assert_eq!(client.peer(&eid), None);

    // Unauthorized set should fail.
    let unauthorized = client.try_set_peer(&eid, &peer, &owner);
    assert_eq!(
        unauthorized.unwrap_err().unwrap(),
        Error::from_type_and_code(ScErrorType::Context, ScErrorCode::InvalidAction)
    );

    // Authorized set should succeed.
    client
        .mock_auths(&[MockAuth {
            address: &owner,
            invoke: &MockAuthInvoke {
                contract: &contract_id,
                fn_name: "set_peer",
                args: (&eid, &peer, &owner).into_val(&env),
                sub_invokes: &[],
            },
        }])
        .set_peer(&eid, &peer, &owner);

    // Assert event before any other contract call (Soroban events are per-call).
    assert_contains_event(&env, &contract_id, PeerSet { eid, peer: peer.clone() });

    // Verify storage without issuing another contract call (so we don't clobber event log).
    env.as_contract(&contract_id, || {
        assert_eq!(OAppCoreStorage::peer(&env, eid), peer.clone());
    });

    // Remove peer by setting None.
    let none: Option<BytesN<32>> = None;
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_peer",
            args: (&eid, &none, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    client.set_peer(&eid, &none, &owner);
    assert_contains_event(&env, &contract_id, PeerSet { eid, peer: None });
    env.as_contract(&contract_id, || {
        assert_eq!(OAppCoreStorage::peer(&env, eid), None);
    });
}

#[test]
fn set_delegate_requires_auth_and_updates_endpoint() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let endpoint_id = env.register(MockEndpoint, ());
    let endpoint_client = MockEndpointClient::new(&env, &endpoint_id);

    let owner = Address::generate(&env);
    client.init(&owner, &endpoint_id);

    // Unauthorized set should fail.
    let delegate = Some(Address::generate(&env));
    let unauthorized = client.try_set_delegate(&delegate, &owner);
    assert_eq!(
        unauthorized.unwrap_err().unwrap(),
        Error::from_type_and_code(ScErrorType::Context, ScErrorCode::InvalidAction)
    );

    // Authorized set should succeed and forward to the endpoint.
    client
        .mock_auths(&[MockAuth {
            address: &owner,
            invoke: &MockAuthInvoke {
                contract: &contract_id,
                fn_name: "set_delegate",
                args: (&delegate, &owner).into_val(&env),
                sub_invokes: &[],
            },
        }])
        .set_delegate(&delegate, &owner);

    assert_eq!(endpoint_client.delegate(&contract_id), delegate);

    // Authorized removal should clear the endpoint delegate.
    let none: Option<Address> = None;
    client
        .mock_auths(&[MockAuth {
            address: &owner,
            invoke: &MockAuthInvoke {
                contract: &contract_id,
                fn_name: "set_delegate",
                args: (&none, &owner).into_val(&env),
                sub_invokes: &[],
            },
        }])
        .set_delegate(&none, &owner);

    assert_eq!(endpoint_client.delegate(&contract_id), None);
}
