// Runtime tests: OAppOptionsType3 defaults generated by `#[oapp]`.

use super::{TestOApp, TestOAppClient};
use oapp::oapp_options_type3::{EnforcedOptionParam, EnforcedOptionSet};
use oapp::OAppError;
use soroban_sdk::{
    testutils::{Address as _, MockAuth, MockAuthInvoke},
    vec, Address, Bytes, Env, IntoVal,
};
use utils::testing_utils::assert_contains_event;

const OPTION_TYPE_3: u16 = 3;
const REMOTE_EID_1: u32 = 100;
const MSG_TYPE_SEND: u32 = 1;
const MSG_TYPE_RECEIVE: u32 = 2;

fn create_valid_options(env: &Env, data: &[u8]) -> Bytes {
    let mut buffer = Bytes::from_array(env, &OPTION_TYPE_3.to_be_bytes());
    buffer.extend_from_slice(data);
    buffer
}

#[test]
fn enforced_options_lifecycle_and_auth() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let owner = Address::generate(&env);
    client.init(&owner, &Address::generate(&env));

    // Unset returns None (storage default).
    assert_eq!(client.enforced_options(&999, &999), None);

    let enforced_1 = create_valid_options(&env, &[1, 2, 3, 4]);
    let enforced_2 = create_valid_options(&env, &[5, 6, 7, 8]);
    let params = vec![
        &env,
        EnforcedOptionParam { eid: REMOTE_EID_1, msg_type: MSG_TYPE_SEND, options: Some(enforced_1.clone()) },
        EnforcedOptionParam { eid: REMOTE_EID_1, msg_type: MSG_TYPE_RECEIVE, options: Some(enforced_2.clone()) },
    ];

    // Unauthorized set should fail (only_auth).
    assert!(client.try_set_enforced_options(&params, &owner).is_err());

    // Non-owner authorized should also fail.
    let non_owner = Address::generate(&env);
    env.mock_auths(&[MockAuth {
        address: &non_owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_enforced_options",
            args: (&params, &non_owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    assert!(client.try_set_enforced_options(&params, &non_owner).is_err());

    // Owner-authorized set should succeed.
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_enforced_options",
            args: (&params, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    client.set_enforced_options(&params, &owner);

    assert_contains_event(&env, &contract_id, EnforcedOptionSet { enforced_options: params.clone() });

    assert_eq!(client.enforced_options(&REMOTE_EID_1, &MSG_TYPE_SEND), Some(enforced_1));
    assert_eq!(client.enforced_options(&REMOTE_EID_1, &MSG_TYPE_RECEIVE), Some(enforced_2));
}

#[test]
fn set_enforced_options_rejects_invalid_option_type() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let owner = Address::generate(&env);
    client.init(&owner, &Address::generate(&env));

    // wrong type header (not 3)
    let mut invalid = Bytes::from_array(&env, &(4u16).to_be_bytes());
    invalid.extend_from_slice(&[1, 2, 3]);

    let params = vec![&env, EnforcedOptionParam { eid: REMOTE_EID_1, msg_type: MSG_TYPE_SEND, options: Some(invalid) }];

    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_enforced_options",
            args: (&params, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    let result = client.try_set_enforced_options(&params, &owner);
    assert_eq!(result.err().unwrap().ok().unwrap(), OAppError::InvalidOptions.into());
}

#[test]
fn combine_options_behavior_and_validation() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let owner = Address::generate(&env);
    client.init(&owner, &Address::generate(&env));

    // No enforced => returns extra (including empty).
    let extra_only = create_valid_options(&env, &[9, 10, 11]);
    assert_eq!(client.combine_options(&REMOTE_EID_1, &MSG_TYPE_SEND, &extra_only), extra_only);
    let empty_extra = Bytes::new(&env);
    assert_eq!(client.combine_options(&REMOTE_EID_1, &MSG_TYPE_SEND, &empty_extra), empty_extra);

    // Set enforced for (eid, msg_type).
    let enforced = create_valid_options(&env, &[1, 2, 3, 4]);
    let params =
        vec![&env, EnforcedOptionParam { eid: REMOTE_EID_1, msg_type: MSG_TYPE_SEND, options: Some(enforced.clone()) }];
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_enforced_options",
            args: (&params, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    client.set_enforced_options(&params, &owner);

    // Enforced present: empty extra => enforced.
    assert_eq!(client.combine_options(&REMOTE_EID_1, &MSG_TYPE_SEND, &Bytes::new(&env)), enforced.clone());

    // Both present: enforced + extra(without its 2-byte header).
    let extra = create_valid_options(&env, &[4, 5, 6]);
    let combined = client.combine_options(&REMOTE_EID_1, &MSG_TYPE_SEND, &extra);
    let expected = create_valid_options(&env, &[1, 2, 3, 4, 4, 5, 6]);
    assert_eq!(combined, expected);

    // Extra has wrong type (len >= 2) => InvalidOptions.
    let mut extra_invalid = Bytes::from_array(&env, &(4u16).to_be_bytes());
    extra_invalid.extend_from_slice(&[9, 9, 9]);
    let bad = client.try_combine_options(&REMOTE_EID_1, &MSG_TYPE_SEND, &extra_invalid);
    assert_eq!(bad.err().unwrap().ok().unwrap(), OAppError::InvalidOptions.into());

    // Extra non-empty but too short (<2) => InvalidOptions.
    let too_short = Bytes::from_array(&env, &[1u8]);
    let bad2 = client.try_combine_options(&REMOTE_EID_1, &MSG_TYPE_SEND, &too_short);
    assert_eq!(bad2.err().unwrap().ok().unwrap(), OAppError::InvalidOptions.into());
}
