// Runtime tests: OAppReceiver defaults generated by `#[oapp]`.

use super::{TestOApp, TestOAppClient};
use endpoint_v2::Origin;
use oapp::OAppError;
use soroban_sdk::{
    contract, contractimpl, symbol_short,
    testutils::{Address as _, MockAuth, MockAuthInvoke},
    token::StellarAssetClient,
    Address, Bytes, BytesN, Env, IntoVal,
};

const REMOTE_EID: u32 = 100;
const REMOTE_EID_FOR_ALLOW_INIT: u32 = 42;

// Minimal mock endpoint used by receiver flow.
#[contract]
pub struct MockEndpoint;

#[contractimpl]
impl MockEndpoint {
    pub fn __constructor(env: Env, native_token: Address) {
        env.storage().instance().set(&symbol_short!("ntk"), &native_token);
    }

    pub fn set_delegate(_env: Env, _oapp: &Address, _delegate: &Option<Address>) {
        // no-op
    }

    pub fn native_token(env: Env) -> Address {
        env.storage().instance().get(&symbol_short!("ntk")).unwrap()
    }

    pub fn clear(env: Env, caller: Address, origin: Origin, receiver: Address, guid: BytesN<32>, message: Bytes) {
        env.storage().instance().set(&symbol_short!("clr_c"), &caller);
        env.storage().instance().set(&symbol_short!("clr_o"), &origin);
        env.storage().instance().set(&symbol_short!("clr_r"), &receiver);
        env.storage().instance().set(&symbol_short!("clr_g"), &guid);
        env.storage().instance().set(&symbol_short!("clr_m"), &message);
    }

    pub fn last_clear(env: Env) -> (Address, Origin, Address, BytesN<32>, Bytes) {
        (
            env.storage().instance().get(&symbol_short!("clr_c")).unwrap(),
            env.storage().instance().get(&symbol_short!("clr_o")).unwrap(),
            env.storage().instance().get(&symbol_short!("clr_r")).unwrap(),
            env.storage().instance().get(&symbol_short!("clr_g")).unwrap(),
            env.storage().instance().get(&symbol_short!("clr_m")).unwrap(),
        )
    }
}

#[test]
fn next_nonce_defaults_to_unordered() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let sender = BytesN::<32>::from_array(&env, &[9u8; 32]);
    assert_eq!(client.next_nonce(&1u32, &sender), 0u64);
}

#[test]
fn is_compose_msg_sender_defaults_to_current_contract() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let origin = Origin { src_eid: 1, sender: BytesN::<32>::from_array(&env, &[1u8; 32]), nonce: 1 };
    let msg = Bytes::from_slice(&env, &[0xAA, 0xBB]);

    // When sender is current contract => true.
    let this = contract_id.clone();
    assert_eq!(client.is_compose_msg_sender(&origin, &msg, &this), true);

    // Different sender => false.
    let other = Address::generate(&env);
    assert_eq!(client.is_compose_msg_sender(&origin, &msg, &other), false);
}

#[test]
fn allow_initialize_path_follows_peer_configuration() {
    let env = Env::default();
    let contract_id = env.register(TestOApp, ());
    let client = TestOAppClient::new(&env, &contract_id);

    let owner = Address::generate(&env);
    let endpoint = Address::generate(&env);
    client.init(&owner, &endpoint);

    let eid: u32 = REMOTE_EID_FOR_ALLOW_INIT;
    let sender = BytesN::<32>::from_array(&env, &[3u8; 32]);

    // No peer set => false.
    let origin = Origin { src_eid: eid, sender: sender.clone(), nonce: 1 };
    assert_eq!(client.allow_initialize_path(&origin), false);

    // Set a non-matching peer => still false.
    let other_sender = BytesN::<32>::from_array(&env, &[4u8; 32]);
    let other_peer = Some(other_sender.clone());
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_peer",
            args: (&eid, &other_peer, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    client.set_peer(&eid, &other_peer, &owner);
    assert_eq!(client.allow_initialize_path(&origin), false);

    // Set matching peer => true.
    let matching_peer = Some(sender.clone());
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &contract_id,
            fn_name: "set_peer",
            args: (&eid, &matching_peer, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    client.set_peer(&eid, &matching_peer, &owner);

    assert_eq!(client.allow_initialize_path(&origin), true);
}

#[test]
fn lz_receive_clears_payload_transfers_value_and_calls_internal_handler() {
    let env = Env::default();

    let owner = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let native_token_sac = env.register_stellar_asset_contract_v2(token_admin.clone());
    let native_token = native_token_sac.address();
    let native_token_admin_client = StellarAssetClient::new(&env, &native_token);

    let endpoint = env.register(MockEndpoint, (&native_token,));
    let oapp = env.register(TestOApp, ());
    let oapp_client = TestOAppClient::new(&env, &oapp);
    oapp_client.init(&owner, &endpoint);

    // Configure peer so peer check passes.
    let peer = BytesN::<32>::from_array(&env, &[9u8; 32]);
    let peer_opt = Some(peer.clone());
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &oapp,
            fn_name: "set_peer",
            args: (&REMOTE_EID, &peer_opt, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    oapp_client.set_peer(&REMOTE_EID, &peer_opt, &owner);

    // Before any lz_receive call, internal handler should not have been invoked.
    assert_eq!(oapp_client.lz_receive_called(), false);

    let executor = Address::generate(&env);
    let origin = Origin { src_eid: REMOTE_EID, sender: peer, nonce: 1 };
    let guid = BytesN::<32>::from_array(&env, &[3u8; 32]);
    let message = Bytes::from_array(&env, &[4, 5, 6]);
    let extra_data = Bytes::new(&env);
    let value: i128 = 123;

    // Mint native token to executor.
    env.mock_auths(&[MockAuth {
        address: &token_admin,
        invoke: &MockAuthInvoke {
            contract: &native_token,
            fn_name: "mint",
            args: (&executor, &value).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    native_token_admin_client.mint(&executor, &value);

    // lz_receive requires executor auth, and will sub-invoke token transfer.
    let transfer_invoke = MockAuthInvoke {
        contract: &native_token,
        fn_name: "transfer",
        args: (&executor, &oapp, &value).into_val(&env),
        sub_invokes: &[],
    };
    env.mock_auths(&[MockAuth {
        address: &executor,
        invoke: &MockAuthInvoke {
            contract: &oapp,
            fn_name: "lz_receive",
            args: (&executor, &origin, &guid, &message, &extra_data, &value).into_val(&env),
            sub_invokes: &[transfer_invoke],
        },
    }]);
    oapp_client.lz_receive(&executor, &origin, &guid, &message, &extra_data, &value);

    // Prove the default `lz_receive` called `Self::__lz_receive`.
    assert_eq!(oapp_client.lz_receive_called(), true);

    // Assert clear() happened.
    let endpoint_client = MockEndpointClient::new(&env, &endpoint);
    let (caller, cleared_origin, receiver, cleared_guid, cleared_message) = endpoint_client.last_clear();
    assert_eq!(caller, oapp);
    assert_eq!(cleared_origin, origin);
    assert_eq!(receiver, oapp);
    assert_eq!(cleared_guid, guid);
    assert_eq!(cleared_message, message);

    // Assert transfer happened.
    let token_client = soroban_sdk::token::TokenClient::new(&env, &native_token);
    assert_eq!(token_client.balance(&executor), 0);
    assert_eq!(token_client.balance(&oapp), value);
}

#[test]
fn lz_receive_wrong_peer_returns_only_peer() {
    let env = Env::default();

    let owner = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let native_token_sac = env.register_stellar_asset_contract_v2(token_admin.clone());
    let native_token = native_token_sac.address();
    let endpoint = env.register(MockEndpoint, (&native_token,));

    let oapp = env.register(TestOApp, ());
    let oapp_client = TestOAppClient::new(&env, &oapp);
    oapp_client.init(&owner, &endpoint);

    // Set peer to some value...
    let configured_peer = BytesN::<32>::from_array(&env, &[7u8; 32]);
    let peer_opt = Some(configured_peer);
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &oapp,
            fn_name: "set_peer",
            args: (&REMOTE_EID, &peer_opt, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    oapp_client.set_peer(&REMOTE_EID, &peer_opt, &owner);

    // ...but call lz_receive with a different sender.
    let executor = Address::generate(&env);
    let origin = Origin { src_eid: REMOTE_EID, sender: BytesN::<32>::from_array(&env, &[8u8; 32]), nonce: 1 };
    let guid = BytesN::<32>::from_array(&env, &[2u8; 32]);
    let message = Bytes::from_array(&env, &[1, 2, 3]);
    let extra_data = Bytes::new(&env);
    let value: i128 = 0;

    env.mock_auths(&[MockAuth {
        address: &executor,
        invoke: &MockAuthInvoke {
            contract: &oapp,
            fn_name: "lz_receive",
            args: (&executor, &origin, &guid, &message, &extra_data, &value).into_val(&env),
            sub_invokes: &[],
        },
    }]);

    let result = oapp_client.try_lz_receive(&executor, &origin, &guid, &message, &extra_data, &value);
    assert_eq!(result.err().unwrap().ok().unwrap(), OAppError::OnlyPeer.into());
}

#[test]
fn lz_receive_no_peer_returns_no_peer() {
    let env = Env::default();

    let owner = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let native_token_sac = env.register_stellar_asset_contract_v2(token_admin.clone());
    let native_token = native_token_sac.address();
    let endpoint = env.register(MockEndpoint, (&native_token,));

    let oapp = env.register(TestOApp, ());
    let oapp_client = TestOAppClient::new(&env, &oapp);
    oapp_client.init(&owner, &endpoint);

    let executor = Address::generate(&env);
    let origin = Origin { src_eid: REMOTE_EID, sender: BytesN::<32>::from_array(&env, &[1u8; 32]), nonce: 1 };
    let guid = BytesN::<32>::from_array(&env, &[2u8; 32]);
    let message = Bytes::from_array(&env, &[1, 2, 3]);
    let extra_data = Bytes::new(&env);
    let value: i128 = 0;

    env.mock_auths(&[MockAuth {
        address: &executor,
        invoke: &MockAuthInvoke {
            contract: &oapp,
            fn_name: "lz_receive",
            args: (&executor, &origin, &guid, &message, &extra_data, &value).into_val(&env),
            sub_invokes: &[],
        },
    }]);

    let result = oapp_client.try_lz_receive(&executor, &origin, &guid, &message, &extra_data, &value);
    assert_eq!(result.err().unwrap().ok().unwrap(), OAppError::NoPeer.into());
}

#[test]
#[should_panic(expected = "HostError: Error(Auth, InvalidAction)")]
fn lz_receive_requires_executor_auth() {
    let env = Env::default();

    let owner = Address::generate(&env);
    let token_admin = Address::generate(&env);
    let native_token_sac = env.register_stellar_asset_contract_v2(token_admin.clone());
    let native_token = native_token_sac.address();
    let endpoint = env.register(MockEndpoint, (&native_token,));

    let oapp = env.register(TestOApp, ());
    let oapp_client = TestOAppClient::new(&env, &oapp);
    oapp_client.init(&owner, &endpoint);

    // Configure peer so we fail specifically at executor.require_auth().
    let peer = BytesN::<32>::from_array(&env, &[7u8; 32]);
    let peer_opt = Some(peer.clone());
    env.mock_auths(&[MockAuth {
        address: &owner,
        invoke: &MockAuthInvoke {
            contract: &oapp,
            fn_name: "set_peer",
            args: (&REMOTE_EID, &peer_opt, &owner).into_val(&env),
            sub_invokes: &[],
        },
    }]);
    oapp_client.set_peer(&REMOTE_EID, &peer_opt, &owner);

    let executor = Address::generate(&env);
    let origin = Origin { src_eid: REMOTE_EID, sender: peer, nonce: 1 };
    let guid = BytesN::<32>::from_array(&env, &[2u8; 32]);
    let message = Bytes::from_array(&env, &[1, 2, 3]);
    let extra_data = Bytes::new(&env);

    // No env.mock_auths for executor => should panic.
    oapp_client.lz_receive(&executor, &origin, &guid, &message, &extra_data, &0);
}
